analyzer:
  errors:
    deprecated_member_use_from_same_package: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_init_to_null
    - directives_ordering
    - slash_for_doc_comments
    - prefer_final_fields
